quarkus:
  datasource:
    db-kind: postgresql
    username: api_test
    password: api_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/db_trainer
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/db_trainer
      max-size: 20
  
  flyway:
    migrate-at-start: true